### ISSUE TITLE
AWS EKS Prometheus and value_error

### ISSUE THREAD

**Issue by mxw-sec** [robusta-dev/krr#346] opened 2024-10-03 19:28 UTC
**Describe the bug**
Running 
`krr simple --history-duration X ` I get the same output regardless.

 WARNING  Not enough history available for cluster arn:aws:eks:us-east-1:{ACCOUNT}:cluster/staging-karpenter.                                             runner.py:235
           WARNING  If the cluster is freshly installed, it might take some time for the enough data to be available.                                                  runner.py:238
           WARNING  Enough data is estimated to be available after 2024-10-04 02:22:55, but will try to calculate recommendations anyway.                              runner.py:241
           INFO     Listing scannable objects in arn:aws:eks:us-east-1:{ACCOUNT}:cluster/staging-karpenter                                                         __init__.py:58
           ERROR    An unexpected error occurred                                                                                                                       runner.py:349
                    Traceback (most recent call last):
                      File "robusta_krr/core/runner.py", line 342, in run
                      File "robusta_krr/core/runner.py", line 288, in _collect_result
                      File "robusta_krr/core/integrations/kubernetes/__init__.py", line 531, in list_scannable_objects
                      File "robusta_krr/core/integrations/kubernetes/__init__.py", line 534, in <listcomp>
                      File "robusta_krr/core/integrations/kubernetes/__init__.py", line 63, in list_scannable_objects
                      File "robusta_krr/core/integrations/kubernetes/__init__.py", line 249, in _list_scannable_objects
                      File "robusta_krr/core/integrations/kubernetes/__init__.py", line 249, in <genexpr>
                      File "robusta_krr/core/integrations/kubernetes/__init__.py", line 172, in __build_scannable_object
                      File "robusta_krr/core/models/allocations.py", line 89, in from_container
                      File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
                    pydantic.error_wrappers.ValidationError: 1 validation error for ResourceAllocations
                    limits
                      invalid literal for int() with base 10: '3200e6' (type=value_error)

**To Reproduce**
run any command such as 

` krr simple --history-duration X`

**Expected behavior**
Output Provided

**Screenshots**
![image](https://github.com/user-attachments/assets/7a104bf8-c47c-4144-8317-75e0e5e385e3)

**Are you interested in contributing a fix for this?**
Yes/no. If yes, we will provide guidance what parts of the code to modify and help you.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser [e.g. chrome, safari] N/A
 - Version [e.g. 22] Latest

**Additional context**

**Comment by aantn** [comment] 2024-10-06 14:49
Weird, I'm not sure what the problem is. The limits field is not an integer, it's a float field which makes the error especially weird.

Do you see any more information when running with --verbose?

**Comment by mxw-sec** [comment] 2024-10-11 15:56
I am running Krr on ubuntu 22.04.5 in WSL, I installed it via brew, and just updated to 1.16.0.. Still getting the same issue.

**Comment by arikalon1** [comment] 2024-10-11 16:44
I think the `3200e6` is a legal limit in k8s, and krr doesn't know to parse it correctly
`3200e6=3200000000`, right?
![Screenshot 2024-10-11 at 7 40 15 PM](https://github.com/user-attachments/assets/4da20e8b-fa80-4c1d-be27-2a19a4155caa)


The issue seems to be while handing a deployment

Can you try running this, and see if indeed you have that memory limit?
`kubectl get deployments -o=jsonpath='{range .items[*]}{.metadata.name}{"\t"}{.spec.template.spec.containers[*].resources.limits.memory}{"\n"}{end}'`

**Comment by arikalon1** [comment] 2024-10-11 16:53
<img width="1031" alt="Screenshot 2024-10-11 at 7 53 15 PM" src="https://github.com/user-attachments/assets/90637827-b35e-4a0e-ae66-ac552355cb44">

**Comment by moshemorad** [comment] 2024-11-12 08:44
Issue was fixed in [#361 ](https://github.com/robusta-dev/krr/pull/361)

**Closed by moshemorad** 2024-11-12 08:44 UTC
